meta_title: "Le premier site de médecins freelance"
meta_description: "Dr Home est le premier site de médecins freelance. Nous vous aidons à trouver vos patients, selon vos disponibilités, en fonction d’où vous vous trouvez pour une tournée de patients optimisée.
Plus besoin de secretariat ou de cabinet, vous pouvez exercer en toute flexibilité et indépendence sans coûts fixes."
meta_image: "banner-image.png" # Une image dans votre dossier app/assets/images/
# twitter_account: "@nomdevotrecompte" # indispensable pour les Twitter Cards

